### ISSUE TITLE
socket.gaierror: [Errno -2] Name or service not known

### ISSUE THREAD

**Issue by NicolasMICAUX** [datakund/youtube-api-datakund#2]
Hi,
When running test code :
```
from youtube_comment_scraper import *
url = 'https://www.youtube.com/watch?v=4SFhwxzfXNc'
# * download comments *
youtube.open(url)
youtube.keypress("pagedown")
response = youtube.video_comments()
data = response['body']
```

I get error
```
Traceback (most recent call last):
  File "/home/nicolas/anaconda3/envs/PACE/lib/python3.8/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/home/nicolas/anaconda3/envs/PACE/lib/python3.8/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/home/nicolas/anaconda3/envs/PACE/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
```

My env is : 
Python 3.8
Ubuntu
datakund, request installed.

**Comment by NicolasMICAUX** [comment]
i'm so dumb ` It currently runs only on windows` in pypi page.
