### ISSUE TITLE
Error when creating object

### ISSUE THREAD

**Issue by def-0** [datakund/youtube-api-datakund#3]
```bash
python3 --version
Python 3.9.2

pip3 list | grep bot-studio
bot-studio          1.2.0
```

```python
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    youtube = bot_studio.youtube ()
  File "/home/def/.local/lib/python3.9/site-packages/bot_studio/bot_studio.py", line 192, in method
    obj1=dynamicclass(*argss,**kwargs)
  File "/home/def/.local/lib/python3.9/site-packages/bot_studio/bot_studio.py", line 107, in set_browser_index
    indexnumber=startbrowser(self,browseroptions)
  File "/home/def/.local/lib/python3.9/site-packages/bot_studio/bot_studio.py", line 73, in startbrowser
    res=requests.post(url = startapi, data = json.dumps(browseroptions), headers=headers)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 456, in prepare_request
    p.prepare(
  File "/usr/lib/python3/dist-packages/requests/models.py", line 316, in prepare
    self.prepare_url(url, params)
  File "/usr/lib/python3/dist-packages/requests/models.py", line 390, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'startbrowser': No schema supplied. Perhaps you meant http://startbrowser?
```

I guess adding a schema won't help.  How is this supposed to work?

**Comment by francistogram** [comment]
I've been running into the same issue running `bot_studio.amazon()` 

Was following the instructions [here](https://amazon-api.datakund.com/en/latest/installation.html#creating-object)
